### ISSUE TITLE
ExciteTranslate Broken

### ISSUE THREAD

**Issue by Scrublord1336** [XUnity-Development/XUnity.AutoTranslator#2]
I am unable to excite translate to work for me. It seems that when using WebClient the "DownloadStringCompleted" event is never called, so it just hangs.

Did this work when it was still using WWW?

**Comment by Vimek** [comment]
Yes, it worked, but very slow.  

 

Try replace:

1. Headers 

headers[ HttpRequestHeader.Accept ] = "text/html";

with

headers[ HttpRequestHeader.Accept ] = "*/*";

2. Url:

https://www.excite.co.jp/world/?wb_lp={0}{1}&before={2}

with

https://www.excite.co.jp/world/english/?wb_lp={0}{1}&before={2}

 

PS: I'm sorry, but after the leave I have a lot of work to do

PS2: Sorry for my english ;)

 

Sent: Tuesday, July 31, 2018 at 11:11 PM

**Comment by Scrublord1336** [comment]
So I fixed this by implementing a new base class for ExcuteTranslateEndpoint called "KnownWwwEndpoint", as opposed to "KnownHttpEndpoint".

This other endpoint uses WWW instead. I have commented out two of the headers because WWW throws a hissy fit as soon as it sees basically any header, that it thinks it should have control over. It works now though.
